# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Emelia Stoner
email: emeliastoner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, freelance web developer, life student 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emeliastoner.com" # the base hostname & protocol for your site
twitter_username: emystoner
github_username: ecstoner

permalink: /:categories/:title
links:
  - title: about
    url: /about
  - title: projects
    url: /projects
  - title: posts
    url: /posts
  - title: contact
    url: /contact

# Build settings
markdown: kramdown
